// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'; // ✅ Correct import for kIsWeb & defaultTargetPlatform

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4GTK81Rl9r-_DbZ4LtSsSo-piRVDPZgc',
    appId: '1:1075954505981:web:01df1b1cb4de8ccf894694',
    messagingSenderId: '1075954505981',
    projectId: 'apeaware-8da95',
    authDomain: 'apeaware-8da95.firebaseapp.com',
    storageBucket: 'apeaware-8da95.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIIwq_5JIfI9OHlq8yLWsSqQ-T4SiF86Y',
    appId: '1:1075954505981:android:c154fd942e736d5e894694',
    messagingSenderId: '1075954505981',
    projectId: 'apeaware-8da95',
    storageBucket: 'apeaware-8da95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfpjqm4Ac2QOBnJFwAvWOLUwa0FDJOc_s',
    appId: '1:1075954505981:ios:5f05ac31af3484d0894694',
    messagingSenderId: '1075954505981',
    projectId: 'apeaware-8da95',
    storageBucket: 'apeaware-8da95.firebasestorage.app',
    iosBundleId: 'com.example.apeaware',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfpjqm4Ac2QOBnJFwAvWOLUwa0FDJOc_s',
    appId: '1:1075954505981:ios:5f05ac31af3484d0894694',
    messagingSenderId: '1075954505981',
    projectId: 'apeaware-8da95',
    storageBucket: 'apeaware-8da95.firebasestorage.app',
    iosBundleId: 'com.example.apeaware',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4GTK81Rl9r-_DbZ4LtSsSo-piRVDPZgc',
    appId: '1:1075954505981:web:e76f534e8f4f1561894694',
    messagingSenderId: '1075954505981',
    projectId: 'apeaware-8da95',
    authDomain: 'apeaware-8da95.firebaseapp.com',
    storageBucket: 'apeaware-8da95.firebasestorage.app',
  );

}